# fly.toml app configuration file generated for genieframework on 2023-07-19T15:16:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "genieframework"
primary_region = "bos"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
